In [1]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

In [2]:
import pandas as pd

from src.data_loader import (
    load_test_reviews,
)

from src.features.tfidf import TFIDFVectorizer
from src.preprocessing.cleaner import preprocess_for_tfidf

In [ ]:
train_df = pd.read_csv("../data/interim/train_split.csv")

valid_df = pd.read_csv("../data/interim/valid_split.csv")

test_df = load_test_reviews()

C:\Users\fam-01\AppData\Local\Temp\ipykernel_21412\2021744711.py:1: DtypeWarning: Columns (0: vote) have mixed types. Specify dtype option on import or set low_memory=False.
  train_df = pd.read_csv("../../data/interim/train_split.csv")
C:\Users\fam-01\AppData\Local\Temp\ipykernel_21412\2021744711.py:3: DtypeWarning: Columns (0: vote) have mixed types. Specify dtype option on import or set low_memory=False.
  valid_df = pd.read_csv("../../data/interim/valid_split.csv")

In [4]:
train_df.head()

,overall,vote,verified,reviewTime,reviewerID,asin,style,reviewerName,reviewText,summary,unixReviewTime
0,4,2,True,2016-08-12,A2UU8H47JDWEUS,B0168G0KZY,{'Format:': ' Personal Computers'},Crosspaws,I found it easy to set up and the 5GHz was a g...,KINDLE FIRE PROBLEMS WITH IT.,1470960000
1,1,NaN,True,2016-01-18,A1FN0P2U6J1R3E,B0176XT9Z0,{'Color:': ' Black/Red'},Chris N,These ear buds look really nice. The come wit...,These ear buds look really nice. The come with...,1453075200
2,5,8,True,2016-11-22,ALK7G9FPDVHYB,B010B7LBYA,NaN,Douglas Patton,"I wear earbuds at work all day, for 8-9 hours....",I am pleased,1479772800
3,5,5,True,2016-08-22,A1VLXWWSKQKL47,B01F6WBE4C,{'Color:': ' Clear'},Photo Gal,I knew I needed this for my Surface Pro becaus...,Nice accessory to keep keyboard clean.,1471824000
4,3,NaN,True,2017-11-14,A1JQ5T52KUK5FI,B00PIIC43U,NaN,SokRobert,It works but you have to know what you're doin...,Works but detects metal too,1510617600

In [5]:
train_df["clean_text"] = train_df["reviewText"].apply(preprocess_for_tfidf)
valid_df["clean_text"] = valid_df["reviewText"].apply(preprocess_for_tfidf)
test_df["clean_text"] = test_df["reviewText"].apply(preprocess_for_tfidf)

In [6]:
train_df[["reviewText","clean_text"]].head()

,reviewText,clean_text
0,I found it easy to set up and the 5GHz was a g...,i found it easy to set up and the 5ghz was a g...
1,These ear buds look really nice. The come wit...,these ear buds look really nice. the come with...
2,"I wear earbuds at work all day, for 8-9 hours....","i wear earbuds at work all day, for 8-9 hours...."
3,I knew I needed this for my Surface Pro becaus...,i knew i needed this for my surface pro becaus...
4,It works but you have to know what you're doin...,it works but you have to know what you're doin...

In [7]:
tfidf = TFIDFVectorizer()

In [8]:
X_train = tfidf.fit_transform(train_df["clean_text"])
X_valid = tfidf.transform(valid_df["clean_text"])
X_test = tfidf.transform(test_df["clean_text"])

In [9]:
print(X_train.shape)
print(X_valid.shape)
print(X_test.shape)

(671155, 50000)
(167789, 50000)
(20000, 50000)

In [10]:
print(tfidf.feature_count)

50000

In [11]:
feature_names = tfidf.feature_names

print(feature_names[:20])
print(feature_names[-20:])

['00' '00 00' '00 and' '00 for' '000' '01' '02' '03' '04' '05' '06' '07'
 '08' '09' '0ghz' '10' '10 00' '10 000' '10 10' '10 100']
['zippers are' 'zips' 'zmodo' 'zone' 'zones' 'zoom' 'zoom and' 'zoom in'
 'zoom is' 'zoom lens' 'zoom range' 'zoom the' 'zoomed' 'zoomed in'
 'zooming' 'zooms' 'zosi' 'zotac' 'zvox' 'zyxel']

In [12]:
print(X_train.nnz)

89088565

In [13]:
density = X_train.nnz / (X_train.shape[0] * X_train.shape[1])
print(density)

0.002654783619283176

In [14]:
print(type(X_train))

<class 'scipy.sparse._csr.csr_matrix'>

In [15]:
tfidf.feature_names[:50]

array(['00', '00 00', '00 and', '00 for', '000', '01', '02', '03', '04',
       '05', '06', '07', '08', '09', '0ghz', '10', '10 00', '10 000',
       '10 10', '10 100', '10 11', '10 12', '10 15', '10 20', '10 and',
       '10 as', '10 bucks', '10 but', '10 computer', '10 days',
       '10 degrees', '10 feet', '10 foot', '10 for', '10 ft', '10 home',
       '10 hours', '10 in', '10 inch', '10 inches', '10 is', '10 it',
       '10 key', '10 laptop', '10 machine', '10 miles', '10 min',
       '10 minutes', '10 month', '10 months'], dtype=object)

In [16]:
tfidf.feature_names[-50:]

array(['yr old', 'yrs', 'yup', 'z170', 'z97', 'zagg', 'zalman', 'zeiss',
       'zenbook', 'zenpad', 'zero', 'zero complaints', 'zero issues',
       'zero problems', 'zero stars', 'zip', 'zip it', 'zip lock',
       'zip tie', 'zip ties', 'zipped', 'zipper', 'zipper and',
       'zipper is', 'zipper on', 'zipper pocket', 'zippered',
       'zippered pocket', 'zippers', 'zippers and', 'zippers are', 'zips',
       'zmodo', 'zone', 'zones', 'zoom', 'zoom and', 'zoom in', 'zoom is',
       'zoom lens', 'zoom range', 'zoom the', 'zoomed', 'zoomed in',
       'zooming', 'zooms', 'zosi', 'zotac', 'zvox', 'zyxel'], dtype=object)

In [19]:
tfidf.save(
    "../artifacts/vectorizers/tfidf.joblib"
)

In [20]:
loaded = TFIDFVectorizer.load(
    "../artifacts/vectorizers/tfidf.joblib"
)

print(loaded.feature_count)

50000