In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("../data/raw/train_data.csv")
products_df = pd.read_csv("../data/raw/title_brand.csv")

C:\Users\fam-01\AppData\Local\Temp\ipykernel_22144\3811621848.py:1: DtypeWarning: Columns (0: vote) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/raw/train_data.csv")

In [3]:
reviews = df.merge(products_df, on="asin", how="left")

In [4]:
reviews = reviews.dropna(subset=["brand"])

In [5]:
brand_counts = reviews.groupby("brand").size().reset_index(name="review_count")

In [6]:
top10_brands = brand_counts.sort_values(by="review_count", ascending=False).head(10)

In [7]:
top_reviews = reviews[reviews["brand"].isin(top10_brands["brand"])]

In [8]:
brand_rating = (
    top_reviews.groupby("brand")["overall"].mean().reset_index(name="average_rating")
)

In [9]:
result = brand_rating.merge(top10_brands, on="brand")

In [10]:
result = result.sort_values(by="average_rating", ascending=False)
result

          brand  average_rating  review_count
1         Anker        4.244320          9860
0  AmazonBasics        4.201468         13213
5       Sabrent        4.028005          7320
7       SanDisk        3.958810          8400
3      Logitech        3.954061         17066
6       Samsung        3.941268         15409
8          Sony        3.938726         12436
9       TP-LINK        3.928681          9773
2          Asus        3.855550         11928
4       NETGEAR        3.836274          7085

In [11]:
result = result[["brand", "average_rating"]].reset_index(drop=True)
result.index += 1
result

           brand  average_rating
1          Anker        4.244320
2   AmazonBasics        4.201468
3        Sabrent        4.028005
4        SanDisk        3.958810
5       Logitech        3.954061
6        Samsung        3.941268
7           Sony        3.938726
8        TP-LINK        3.928681
9           Asus        3.855550
10       NETGEAR        3.836274